const STORE = {
  name: "ELI COLLECTION",
  place: "KAMUKUNJI",
  tagline: "Carpets, mats & wall-to-wall",
  phoneDisplay: "0725 856 946",
  phoneLocal: "0725856946",
  whatsapp: "254725856946",
  address: "Kamukunji Market, Nairobi, Kenya",
  hours: "Mon–Sat 8:00am – 6:30pm · Sun 10:00am – 4:00pm",
  // Delivery is available; a flat Nairobi drop-off fee is quoted at checkout.
  // Set to 0 if you ever want to offer free delivery.
  nairobiFee: 400,
  deliveryText: "DELIVERY AVAILABLE",
};

const CATEGORIES = [
  { id: "turkish", name: "Turkish & Persian Carpets", blurb: "5×8 · 6×9 · 7×10 for the sitting room", image: "assets/images/turkish-maroon.jpg" },
  { id: "shaggy", name: "Fluffy & Shaggy Carpets", blurb: "Fluffy, shaggy and fur — bedroom & TV room", image: "assets/images/shaggy-cream.jpg" },
  { id: "printed", name: "3D & HD Carpets", blurb: "Printed designs, latest colours in stock", image: "assets/images/carpet-3d.jpg" },
  { id: "walltowall", name: "Wall to Wall Carpet", blurb: "Delta, VIP & carpet tiles — cut to size", image: "assets/images/wall-to-wall-rolls.jpg" },
  { id: "mosque", name: "Mosque Carpet & Musalla", blurb: "Mosque rolls, prayer mats & travel musalla", image: "assets/images/mosque-carpet.jpg" },
  { id: "runners", name: "Runners & Bedside", blurb: "Bedside fur, 60×180 and red carpet by the metre", image: "assets/images/bedside-fluffy.jpg" },
  { id: "bathroom", name: "Bathroom Mats", blurb: "Coral fleece, diatomite & anti-slip sets", image: "assets/images/bathroom-mat.jpg" },
  { id: "doormats", name: "Door & Kitchen Mats", blurb: "Door mats, PVC and anti-slip kitchen sets", image: "assets/images/door-mat.jpg" },
];

const PRODUCTS = [
  {
    id: "crown-turkish",
    name: "Crown Turkish Carpet",
    category: "turkish",
    price: 10500,
    compareAt: 12500,
    badge: "Bestseller",
    featured: true,
    stock: 12,
    image: "assets/images/turkish-maroon.jpg",
    images: ["assets/images/turkish-maroon.jpg", "assets/images/showroom-floor.jpg", "assets/images/hero.jpg"],
    material: "Machine-woven Turkish pile, heat-set",
    pile: "Medium · 10 mm",
    origin: "Turkish mill · Kamukunji stock",
    colors: ["Maroon", "Gold", "Cream", "Navy"],
    sizes: [
      { id: "58", label: "5 × 8 ft (152 × 244 cm)", price: 10500, default: true },
      { id: "69", label: "6 × 9 ft (183 × 274 cm)", price: 14500 },
      { id: "710", label: "7 × 10 ft (213 × 305 cm)", price: 18500 },
    ],
    summary: "The Crown is the carpet Kamukunji sells out of first — maroon and gold, heavy in the hand, laid in a thousand Nairobi sitting rooms.",
    description:
      "Crown Turkey is the benchmark in this market. Dense machine-woven pile with a classic central medallion and bordered edge, in the maroon-and-gold that Nairobi calls a sitting-room carpet. It holds its pattern under a coffee table and under children, and it vacuums clean. We keep the 5×8 on the floor every week — that is the size most Kenyan sitting rooms actually take.",
    care: "Vacuum weekly without a beater bar. Blot spills straight away. Rotate 180° every few months so the Nairobi sun fades it evenly. Professional wash once a year.",
  },
  {
    id: "persian-medallion",
    name: "Persian Carpet (Medallion)",
    category: "turkish",
    price: 12500,
    compareAt: 15000,
    badge: "Classic",
    featured: true,
    stock: 6,
    image: "assets/images/persian-medallion.jpg",
    images: ["assets/images/persian-medallion.jpg", "assets/images/hero.jpg"],
    material: "Persian-design woven pile",
    pile: "Medium · 12 mm",
    origin: "Persian design · Nairobi stock",
    colors: ["Burgundy", "Navy", "Antique gold"],
    sizes: [
      { id: "58", label: "5 × 8 ft (152 × 244 cm)", price: 12500, default: true },
      { id: "710", label: "7 × 10 ft (213 × 305 cm)", price: 20500 },
      { id: "811", label: "8 × 11 ft (244 × 335 cm)", price: 23500 },
    ],
    summary: "Burgundy, navy and gold with a layered medallion — the carpet people buy when they want the room to look finished.",
    description:
      "A traditional Persian layout: scalloped medallion, floral field, three borders. The pile is dense enough for daily sitting-room traffic and soft under bare feet. On dark timber it reads formal; on cream Nairobi tiles it warms the whole room. Available in the three sizes Kenyan houses ask for — 5×8, 7×10 and 8×11.",
    care: "Vacuum with the pile. Blot, do not rub. Professional clean for oil or heavy soiling.",
  },
  {
    id: "turkish-gold-plain",
    name: "Turkish Gold Plain Carpet",
    category: "turkish",
    price: 8500,
    compareAt: 10000,
    badge: "New",
    featured: false,
    stock: 9,
    image: "assets/images/turkish-gold.jpg",
    images: ["assets/images/turkish-gold.jpg", "assets/images/showroom-floor.jpg"],
    material: "Plain Turkish pile with subtle texture",
    pile: "Medium · 9 mm",
    origin: "Turkish mill · Kamukunji stock",
    colors: ["Gold", "Cream", "Beige", "Grey"],
    sizes: [
      { id: "58", label: "5 × 8 ft (152 × 244 cm)", price: 8500, default: true },
      { id: "69", label: "6 × 9 ft (183 × 274 cm)", price: 11500 },
      { id: "710", label: "7 × 10 ft (213 × 305 cm)", price: 14500 },
    ],
    summary: "Plain gold, no pattern — the one interior designers in Nairobi keep ordering for bright, quiet rooms.",
    description:
      "One colour, one texture, no medallion. Plain Turkish carpet is what you want when the sofa is patterned or the room is small and you need light, not noise. The subtle weave stops it reading flat on a big floor. Popular for apartments in Kilimani, Westlands and Kileleshwa.",
    care: "Vacuum freely. Most spills lift with a damp cloth. Rotate twice a year.",
  },
  {
    id: "turkish-shaggy-58",
    name: "Turkish Shaggy Carpet 5×8",
    category: "shaggy",
    price: 9600,
    compareAt: 11000,
    badge: "Softest",
    featured: true,
    stock: 8,
    image: "assets/images/shaggy-cream.jpg",
    images: ["assets/images/shaggy-cream.jpg"],
    material: "Turkish shaggy pile",
    pile: "High · 35 mm",
    origin: "Turkish mill · in store now",
    colors: ["Cream", "Grey", "Beige", "Coffee"],
    sizes: [
      { id: "46", label: "4 × 6 ft (122 × 183 cm)", price: 5500 },
      { id: "58", label: "5 × 8 ft (152 × 244 cm)", price: 9600, default: true },
      { id: "69", label: "6 × 9 ft (183 × 274 cm)", price: 12500 },
    ],
    summary: "Proper Turkish shaggy — long, heavy pile that people stand on in the shop and refuse to leave.",
    description:
      "Bedroom, TV room, or the corner of the sitting room where the children sit. The shaggy pile is long, light-catching and soft underfoot in a way flat carpet never manages. Best on a non-slip underlay — we stock those. Keep it indoors; this is not a veranda carpet.",
    care: "Gentle vacuum on suction only. Shake outdoors to revive the pile. Keep away from open flames and heavy office chairs.",
  },
  {
    id: "fluffy-comfy",
    name: "Fluffy Comfy Carpet",
    category: "shaggy",
    price: 2500,
    compareAt: 3200,
    badge: "Kamukunji price",
    featured: true,
    stock: 30,
    image: "assets/images/fluffy-grey.jpg",
    images: ["assets/images/fluffy-grey.jpg", "assets/images/folded-mats.jpg"],
    material: "Fluffy soft-touch pile, non-slip backing",
    pile: "Fluffy · medium-high",
    origin: "Kamukunji bestseller",
    colors: ["Grey", "Maroon", "Beige", "Coffee", "Red"],
    sizes: [
      { id: "58", label: "5 × 8 ft (152 × 244 cm)", price: 2500, default: true },
      { id: "78", label: "7 × 8 ft (213 × 244 cm)", price: 3800 },
      { id: "710", label: "7 × 10 ft (213 × 305 cm)", price: 4500 },
    ],
    summary: "The fluffy carpet that made Kamukunji famous on TikTok — soft, non-slip, and priced for every room in the house.",
    description:
      "This is the volume seller. Fluffy pile with a grippy backing, in the colours Nairobi buys: grey, maroon, beige, coffee and red. Landlords put them in rentals, students take the 5×8 to bedsitters, families buy two — one for the sitting room, one for the bedroom. Washable, packable, and cheap enough to replace.",
    care: "Shake out and vacuum. Hand-wash or gentle machine wash cold, then shade-dry. Do not tumble on high heat.",
  },
  {
    id: "american-fur-58",
    name: "American Style Luxury Fur Carpet 5×8",
    category: "shaggy",
    price: 4500,
    compareAt: null,
    badge: "New",
    featured: false,
    stock: 10,
    image: "assets/images/fur-carpet.jpg",
    images: ["assets/images/fur-carpet.jpg", "assets/images/shaggy-cream.jpg"],
    material: "Long faux fur, suede-feel backing",
    pile: "Fur · long",
    origin: "Latest import · Kamukunji stock",
    colors: ["Grey", "Cream", "Beige"],
    sizes: [
      { id: "34", label: "90 × 120 cm (fur rug)", price: 3200 },
      { id: "58", label: "5 × 8 ft (152 × 244 cm)", price: 4500, default: true },
    ],
    summary: "Grey, cream and beige faux fur — soft feel, soft look, the one that photographs well.",
    description:
      "Luxury faux fur with a sleek finish, in the three colours that suit Kenyan rentals and Airbnbs. Lay the 5×8 in front of the sofa, or take the 90×120 as a bedside or dressing-area rug. Non-slip backing so it stays put on tiles and laminate.",
    care: "Shake and gentle vacuum. Spot-clean with mild soap. Do not machine-wash the long fur.",
  },
  {
    id: "carpet-3d-58",
    name: "3D Carpet 5×8",
    category: "printed",
    price: 3500,
    compareAt: 4500,
    badge: "Trending",
    featured: true,
    stock: 18,
    image: "assets/images/carpet-3d.jpg",
    images: ["assets/images/carpet-3d.jpg", "assets/images/hd-carpet.jpg"],
    material: "3D high-definition printed pile",
    pile: "Low-medium · 8 mm",
    origin: "Latest prints · Kamukunji stock",
    colors: ["Teal", "Charcoal", "Cream", "Ocean blue"],
    sizes: [
      { id: "58", label: "5 × 8 ft (152 × 244 cm)", price: 3500, default: true },
      { id: "710", label: "7 × 10 ft (213 × 305 cm)", price: 4500 },
    ],
    summary: "Printed 3D designs with real depth — the pattern everyone is asking for by name in Kamukunji.",
    description:
      "A printed carpet that actually looks three-dimensional: layered cubes, waves and abstracts that seem to lift off the floor. Low pile, so crumbs and dust behave, and the busy pattern hides marks between cleans. Ocean blue, teal and charcoal are the colours we restock fastest.",
    care: "Vacuum freely. Wipe spills with a damp cloth. Suitable for covered verandas.",
  },
  {
    id: "hd-carpet-58",
    name: "HD Carpet 5×8",
    category: "printed",
    price: 3800,
    compareAt: null,
    badge: null,
    featured: false,
    stock: 14,
    image: "assets/images/hd-carpet.jpg",
    images: ["assets/images/hd-carpet.jpg"],
    material: "HD printed low-pile carpet",
    pile: "Low · 7 mm",
    origin: "Printed collection · Kamukunji stock",
    colors: ["Marble grey", "Navy", "White", "Gold"],
    sizes: [{ id: "58", label: "5 × 8 ft (152 × 244 cm)", price: 3800, default: true }],
    summary: "Marble and abstract HD prints — sharp, modern, and cheap enough to change with the mood.",
    description:
      "High-definition printing gives crisp marble swirls and abstracts that flat dyeing cannot. Low pile, easy to move, easy to clean. A good first carpet for a bedsitter or a first apartment in Nairobi.",
    care: "Vacuum. Spot-clean with a damp cloth. Do not bleach.",
  },
  {
    id: "delta-wall-to-wall",
    name: "Delta Wall to Wall Carpet (10mm)",
    category: "walltowall",
    price: 1300,
    compareAt: null,
    badge: "Cut to size",
    featured: true,
    stock: 40,
    image: "assets/images/wall-to-wall-rolls.jpg",
    images: ["assets/images/wall-to-wall-rolls.jpg", "assets/images/shop-interior.jpg"],
    material: "Delta grade wall-to-wall from the roll, 10 mm",
    pile: "10 mm loop pile",
    origin: "Kamukunji cutting yard",
    colors: ["Maroon", "Grey", "Beige", "Brown", "Green"],
    sizes: [
      { id: "m2", label: "Per square metre (carpet only)", price: 1300, default: true },
      { id: "bed12", label: "Bedroom ~12 m²", price: 15600 },
      { id: "lounge20", label: "Lounge ~20 m²", price: 26000 },
    ],
    summary: "Delta 10 mm off the roll, cut to your room. The most fitted carpet in Kenya — bedrooms, offices, churches.",
    description:
      "The rolls standing at the back of the shop are not decoration. Delta 10 mm is the workhorse wall-to-wall in this market: bedrooms, offices, church halls, hotel corridors and car-boot liners. Price is per square metre; send length × width on WhatsApp and we quote the exact cut, including underlay and fitting.",
    care: "Vacuum regularly. Professional shampoo every 12–18 months. We include a care slip with every cut.",
  },
  {
    id: "vip-wall-to-wall",
    name: "VIP Wall to Wall Carpet",
    category: "walltowall",
    price: 4800,
    compareAt: 5200,
    badge: "Executive",
    featured: false,
    stock: 20,
    image: "assets/images/wall-to-wall-rolls.jpg",
    images: ["assets/images/wall-to-wall-rolls.jpg", "assets/images/showroom-floor.jpg"],
    material: "VIP grade plush wall-to-wall",
    pile: "Thick · 12 mm plush",
    origin: "Executive grade · Kamukunji stock",
    colors: ["Red", "Maroon", "Grey", "Blue", "Beige"],
    sizes: [
      { id: "m2", label: "Per square metre", price: 4800, default: true },
      { id: "bed12", label: "Bedroom ~12 m²", price: 57600 },
    ],
    summary: "The thick executive grade — what hotels and boardrooms fit when the budget allows.",
    description:
      "VIP is the upgrade from Delta: heavier face weight, deeper pile, quieter underfoot. Used in executive offices, hotel rooms and the main bedroom where people walk barefoot. Sold by the square metre, cut in our yard and fitted by our team across Nairobi.",
    care: "Vacuum with the pile. Professional clean annually. Avoid dragging heavy furniture across it.",
  },
  {
    id: "carpet-tiles",
    name: "Carpet Tiles 50×50",
    category: "walltowall",
    price: 2500,
    compareAt: 3000,
    badge: "Office",
    featured: false,
    stock: 60,
    image: "assets/images/carpet-tiles.jpg",
    images: ["assets/images/carpet-tiles.jpg"],
    material: "Commercial carpet tiles, bitumen backing",
    pile: "Low loop · commercial",
    origin: "Office flooring · supplied & fitted",
    colors: ["Grey", "Charcoal", "Blue", "Mixed"],
    sizes: [
      { id: "m2", label: "Per square metre", price: 2500, default: true },
      { id: "office20", label: "Office ~20 m² supplied & fitted", price: 50000 },
    ],
    summary: "50 × 50 tiles for offices and boardrooms — lift one and replace it, no need to redo the floor.",
    description:
      "Carpet tiles are the practical choice for Nairobi offices: heavy traffic, rolling chairs, and when someone spills coffee you replace a single 50×50 tile instead of a whole room. Supplied and fitted per square metre, with acoustic options for boardrooms and podcast rooms.",
    care: "Vacuum daily in traffic lanes. Lift and replace damaged tiles as needed. Professional clean annually.",
  },
  {
    id: "mosque-carpet",
    name: "Mosque Carpet (per metre)",
    category: "mosque",
    price: 2700,
    compareAt: null,
    badge: "Roll",
    featured: true,
    stock: 25,
    image: "assets/images/mosque-carpet.jpg",
    images: ["assets/images/mosque-carpet.jpg", "assets/images/shop-interior.jpg"],
    material: "Mosque-grade roll carpet with saff (row) lines",
    pile: "10 mm · dense",
    origin: "Mosque roll · cut to length",
    colors: ["Green", "Maroon", "Navy", "Beige"],
    sizes: [
      { id: "bare", label: "Per metre (carpet only)", price: 2700, default: true },
      { id: "fitted", label: "Per metre — supplied & fitted", price: 2900 },
    ],
    summary: "Saff-lined mosque roll sold by the metre — minimum 4 metres. We cut, roll and fit across Nairobi.",
    description:
      "The roll mosques, madrasas and musallas in Nairobi actually buy: dense 10 mm pile with printed saff lines so rows stay straight. Green, maroon, navy and beige in stock. Sold by the metre from a 1.33 m wide roll, minimum 4 metres. Send the hall measurements on WhatsApp and we quote the full floor, fitted.",
    care: "Vacuum along the rows. Professional shampoo annually. Rotate high-traffic strips near the entrance.",
  },
  {
    id: "prayer-mat-velvet",
    name: "Assorted Prayer Mat 70 × 115 cm",
    category: "mosque",
    price: 1625,
    compareAt: 1900,
    badge: "Bestseller",
    featured: true,
    stock: 50,
    image: "assets/images/prayer-mat.jpg",
    images: ["assets/images/prayer-mat.jpg", "assets/images/mosque-carpet.jpg"],
    material: "Velvet face with foam padding",
    pile: "Padded · ~15 mm",
    origin: "Prayer collection · Eastleigh & Kamukunji stock",
    colors: ["Emerald", "Maroon", "Navy", "Gold detail"],
    sizes: [
      { id: "single", label: "70 × 115 cm (single)", price: 1625, default: true },
      { id: "set2", label: "Set of 2", price: 3100 },
    ],
    summary: "Padded velvet musalla with a woven mihrab — the mat Eastleigh, South C and the CBD empty our shelves of every Friday.",
    description:
      "Soft velvet face over a foam core, with a shaped mihrab arch and matching tassels. Comfortable to stand and prostrate on, and tidy enough to leave out in a sitting room. Comes in assorted designs — tell us your colour on WhatsApp and we pick accordingly.",
    care: "Gentle brush or low vacuum. Do not wring. Air in shade if damp. Do not machine-wash the padded ones.",
  },
  {
    id: "travel-prayer-mat",
    name: "Foldable Travel Prayer Mat",
    category: "mosque",
    price: 899,
    compareAt: 1000,
    badge: null,
    featured: false,
    stock: 45,
    image: "assets/images/prayer-mat-travel.jpg",
    images: ["assets/images/prayer-mat-travel.jpg", "assets/images/prayer-mat.jpg"],
    material: "Lightweight quilted fabric",
    pile: "Thin · folds flat",
    origin: "Travel collection",
    colors: ["Navy", "Green", "Assorted prints"],
    sizes: [{ id: "std", label: "Folds to laptop size · opens ~60 × 100 cm", price: 899, default: true }],
    summary: "Folds down to laptop size — for the glove box, the office drawer or the suitcase.",
    description:
      "Light, cleanable and dignified. Folds flat into a pouch so it lives in a bag or a car door without complaint. We sell these in twos: one for the office, one for travel.",
    care: "Wipe with a barely damp cloth. Air dry. Do not iron any printed detail.",
  },
  {
    id: "bedside-fluffy-46",
    name: "Fluffy Bedside Carpet (4 × 6)",
    category: "runners",
    price: 1800,
    compareAt: 2300,
    badge: "Value",
    featured: true,
    stock: 35,
    image: "assets/images/bedside-fluffy.jpg",
    images: ["assets/images/bedside-fluffy.jpg", "assets/images/fluffy-grey.jpg"],
    material: "Fluffy high pile, non-slip backing",
    pile: "Fluffy · high",
    origin: "Kamukunji bestseller",
    colors: ["Grey", "Cream", "Pink", "Coffee"],
    sizes: [
      { id: "46", label: "4 × 6 ft (122 × 183 cm)", price: 1800, default: true },
      { id: "set2", label: "Set of 2 (4 × 6 ft)", price: 3400 },
    ],
    summary: "The bedside size — the first thing your feet touch in the morning, for under two thousand shillings.",
    description:
      "Sized for the gap beside the bed, not the whole floor. Fluffy pile with a non-slip back so it stays put on tiles and laminate. Buy two and do both sides of the bed, or one for the bedside and one for the dressing table.",
    care: "Shake outdoors. Gentle vacuum. Hand-wash cold and shade-dry.",
  },
  {
    id: "rabbit-fur-60180",
    name: "Ultra Soft Rabbit Fur Carpet (60 × 180 cm)",
    category: "runners",
    price: 2800,
    compareAt: null,
    badge: "Popular",
    featured: true,
    stock: 22,
    image: "assets/images/fur-carpet.jpg",
    images: ["assets/images/fur-carpet.jpg"],
    material: "Faux rabbit fur, non-slip backing",
    pile: "Fur · long, irregular shape",
    origin: "Bedside collection · Kamukunji stock",
    colors: ["White", "Maroon", "Pink", "Grey"],
    sizes: [{ id: "60180", label: "60 × 180 cm", price: 2800, default: true }],
    summary: "The 60 × 180 runner everyone buys for the bedside, the dressing area and the dashboard.",
    description:
      "Long, soft faux fur with a grippy back — the multipurpose piece. Beside the bed, along the dressing table, at the foot of the sofa, or across a car dashboard to keep the sun off. Non-slip, holds its fluff, and washes back to soft.",
    care: "Shake and gentle vacuum. Hand-wash cold, reshape and shade-dry. Do not tumble dry.",
  },
  {
    id: "red-carpet-metre",
    name: "Delta Red Carpet (per metre)",
    category: "runners",
    price: 1050,
    compareAt: null,
    badge: "Events",
    featured: false,
    stock: 30,
    image: "assets/images/red-carpet.jpg",
    images: ["assets/images/red-carpet.jpg", "assets/images/wall-to-wall-rolls.jpg"],
    material: "Delta red carpet roll",
    pile: "Low · event grade",
    origin: "Kamukunji roll · cut to length",
    colors: ["Red"],
    sizes: [
      { id: "fitted", label: "Per metre — inclusive of installation", price: 1050, default: true },
      { id: "bare", label: "Per metre — carpet only", price: 900 },
    ],
    summary: "Red carpet by the metre — church aisles, weddings, hotel entrances and school events.",
    description:
      "The classic Delta red, sold off the roll by the metre. We cut aisles for weddings and church services, entrance runs for hotels and graduations, and corridor lengths for schools. Price is per metre with installation, or carpet only if you are laying it yourself.",
    care: "Vacuum after use. Roll, do not fold, for storage. Spot-clean promptly.",
  },
  {
    id: "coral-fleece-round",
    name: "Coral Fleece Bathroom Mat (40 cm round)",
    category: "bathroom",
    price: 700,
    compareAt: 1800,
    badge: "Deal",
    featured: true,
    stock: 40,
    image: "assets/images/bathroom-mat.jpg",
    images: ["assets/images/bathroom-mat.jpg"],
    material: "Coral fleece, non-slip base",
    pile: "Soft fleece",
    origin: "Bathroom collection",
    colors: ["Grey", "White", "Pink", "Blue", "Coffee"],
    sizes: [
      { id: "round", label: "40 cm round (single)", price: 700, default: true },
      { id: "set2", label: "Set of 2", price: 1300 },
    ],
    summary: "Soft coral fleece, non-slip base, hotel feel — the bathroom mat everyone grabs on the way past the bench.",
    description:
      "Round, plush, and quick-drying, with a proper non-slip base so it does not travel across wet tiles. Fits beside a shower, in front of a basin, or under a dressing table. Ask for a matching pair — most people do.",
    care: "Machine-wash cold in a laundry bag. Do not tumble on high. Lay flat to dry.",
  },
  {
    id: "diatomite-80120",
    name: "2-in-1 Diatomite Mat (80 × 120 cm)",
    category: "bathroom",
    price: 2100,
    compareAt: null,
    badge: "Quick dry",
    featured: true,
    stock: 16,
    image: "assets/images/diatomite-mat.jpg",
    images: ["assets/images/diatomite-mat.jpg"],
    material: "Diatomite (diatom earth) with anti-slip rubber back",
    pile: "Hard surface · absorbent",
    origin: "Bathroom & kitchen collection",
    colors: ["Grey", "Beige", "Printed"],
    sizes: [{ id: "set", label: "2-in-1 set — 80 × 120 cm + 50 × 80 cm", price: 2100, default: true }],
    summary: "Water disappears off a diatomite mat — no damp smell, no wet feet, no washing.",
    description:
      "Diatom earth soaks up water in seconds and dries itself, with an anti-slip rubber back that grips wet tiles. The big 80×120 is large enough to stand on alone in the bathroom, corridor or kitchen; the 50×80 goes at the door. Prints available.",
    care: "Air dry upright. If it slows down absorbing, a light sanding refreshes the surface. Do not machine-wash.",
  },
  {
    id: "kitchen-anti-slip",
    name: "Kitchen Anti-Slip Mat Set",
    category: "doormats",
    price: 850,
    compareAt: null,
    badge: "Set",
    featured: false,
    stock: 28,
    image: "assets/images/kitchen-mat.jpg",
    images: ["assets/images/kitchen-mat.jpg", "assets/images/rack-mats.jpg"],
    material: "Anti-slip rubber-backed mats",
    pile: "Low · waterproof",
    origin: "Kitchen collection",
    colors: ["Assorted prints", "Grey", "Brown"],
    sizes: [
      { id: "set2", label: "Set of 2 — 120 × 40 cm + 60 × 40 cm", price: 850, default: true },
      { id: "rubber", label: "Rubber-bottom set (2 pcs · 50 × 120 cm)", price: 1700 },
    ],
    summary: "Anti-slip kitchen mats — waterproof, wipe-clean, and they stay put between the sink and the cooker.",
    description:
      "Standing for a long time on hard kitchen tiles is punishment. These mats cushion it, catch the splashes and wipe clean, and the rubber back means nobody slides. Sold as a long-and-short set so the cooker run and the sink both get covered.",
    care: "Wipe with a damp cloth or hose down. Air dry flat. Do not bleach.",
  },
  {
    id: "door-mat",
    name: "Door Mat",
    category: "doormats",
    price: 2100,
    compareAt: 2200,
    badge: null,
    featured: false,
    stock: 24,
    image: "assets/images/door-mat.jpg",
    images: ["assets/images/door-mat.jpg", "assets/images/rack-mats.jpg"],
    material: "Coir and rubber-backed door mats",
    pile: "Scrape pile",
    origin: "Door collection",
    colors: ["Natural coir", "Black rubber", "Grey", "Printed"],
    sizes: [
      { id: "std", label: "45 × 75 cm", price: 2100, default: true },
      { id: "heavy", label: "Heavy-duty PVC (per metre)", price: 450 },
    ],
    summary: "Proper door mats that scrape Nairobi dust off shoes before it reaches your tiles.",
    description:
      "Thick coir in a rubber frame for the front door, or heavy-duty PVC by the metre for the back door, veranda and office entrance. This is the mat that does the work so the carpet inside lasts longer.",
    care: "Beat outdoors. Hose if needed and dry in the sun. Coir sheds lightly when new — that is normal.",
  },
];

const TESTIMONIALS = [
  {
    quote: "I came for a door mat and left with a Crown Turkish carpet. They let me stand on three sizes until the colour was right. Delivery to South C the same afternoon.",
    name: "Amina K.",
    place: "South C, Nairobi",
  },
  {
    quote: "Bought mosque carpet for the madrasa — 20 metres, cut and fitted in two days. Prices are Kamukunji-fair and they packed it properly for town.",
    name: "Hassan M.",
    place: "Eastleigh, Nairobi",
  },
  {
    quote: "The fluffy bedside carpet is the first thing guests notice. WhatsApped my bedroom photo, they told me the size. That kind of help is rare.",
    name: "Brian O.",
    place: "Westlands",
  },
  {
    quote: "We outfit rentals. The fluffy carpets and kitchen mat sets survive tenants and still look considered. I reorder every quarter.",
    name: "Faith W.",
    place: "Kitengela",
  },
];
