const STORE = {
  name: "ELI COLLECTION",
  place: "KAMUKUNJI",
  tagline: "Floor carpets and mats",
  phoneDisplay: "0725 856 946",
  phoneLocal: "0725856946",
  whatsapp: "254725856946",
  address: "Kamukunji Market, Nairobi, Kenya",
  hours: "Mon–Sat 8:00am – 6:30pm · Sun 10:00am – 4:00pm",
  freeDeliveryFrom: 10000,
  nairobiFee: 400,
};

const CATEGORIES = [
  { id: "persian", name: "Persian & Oriental", blurb: "Medallion heirlooms for living rooms", image: "assets/images/persian-royal.jpg" },
  { id: "modern", name: "Modern Area Rugs", blurb: "Clean geometry for contemporary homes", image: "assets/images/geometric-nairobi.jpg" },
  { id: "tribal", name: "Tribal & Kilim", blurb: "Bold weaves with East African spirit", image: "assets/images/tribal-maasai.jpg" },
  { id: "shag", name: "Shag & Plush", blurb: "Cloud-soft pile underfoot", image: "assets/images/shag-cloud.jpg" },
  { id: "prayer", name: "Prayer Mats", blurb: "Padded, travel and family sizes", image: "assets/images/prayer-alnoor.jpg" },
  { id: "door", name: "Door Mats", blurb: "Coir, rubber-back and indoor packs", image: "assets/images/doormat-coir.jpg" },
  { id: "bath", name: "Bathroom Mats", blurb: "Memory foam and shag spa sets", image: "assets/images/bath-memory.jpg" },
  { id: "runners", name: "Runners", blurb: "Hallways, kitchens and corridors", image: "assets/images/kitchen-runner.jpg" },
];

const PRODUCTS = [
  {
    id: "royal-persian",
    name: "Royal Persian Medallion Rug",
    category: "persian",
    price: 24500,
    compareAt: 28900,
    badge: "Bestseller",
    featured: true,
    stock: 6,
    image: "assets/images/persian-royal.jpg",
    images: ["assets/images/persian-royal.jpg", "assets/images/hero.jpg", "assets/images/showroom-floor.jpg"],
    material: "Heat-set wool-feel pile",
    pile: "Medium · 12 mm",
    origin: "Imported design · finished for Kenyan homes",
    colors: ["Burgundy", "Navy", "Antique gold"],
    sizes: [
      { id: "sm", label: "160 × 230 cm", price: 18500 },
      { id: "md", label: "200 × 300 cm", price: 24500, default: true },
      { id: "lg", label: "250 × 350 cm", price: 32800 },
    ],
    summary: "A classic central medallion in burgundy, navy and gold — the rug that makes a sitting room feel finished.",
    description:
      "Woven in a traditional Persian layout with a scalloped medallion, floral field and layered borders. The pile is dense enough for daily living-room traffic yet soft under bare feet. Laid on dark timber it reads ceremonial; on cream tiles it warms the whole room. A signature piece from our Kamukunji floor.",
    care: "Vacuum weekly without a beater bar. Blot spills immediately. Professional wash recommended once a year. Rotate 180° every few months so the sun fades evenly.",
  },
  {
    id: "kilim-istanbul",
    name: "Anatolia Kilim Weave",
    category: "tribal",
    price: 14200,
    compareAt: 16800,
    badge: "New",
    featured: true,
    stock: 9,
    image: "assets/images/kilim-istanbul.jpg",
    images: ["assets/images/kilim-istanbul.jpg", "assets/images/about-store.jpg"],
    material: "Flatweave cotton-blend kilim",
    pile: "Flat · reversible",
    origin: "Anatolian-inspired · Nairobi stock",
    colors: ["Terracotta", "Ink", "Cream", "Mustard"],
    sizes: [
      { id: "sm", label: "120 × 180 cm", price: 9800 },
      { id: "md", label: "160 × 230 cm", price: 14200, default: true },
      { id: "lg", label: "200 × 290 cm", price: 18900 },
    ],
    summary: "Flatweave diamonds in terracotta and ink — light, reversible, and perfect where you want pattern without thickness.",
    description:
      "A true kilim: no pile, just a tight geometric weave you can flip when one face tires. The terracotta field and charcoal bands sit beautifully in Nairobi apartments, Airbnbs and office waiting rooms. Easy to roll, easy to shake out, easy to love.",
    care: "Shake outdoors and vacuum both sides. Spot-clean with mild soap. Do not machine-wash large sizes.",
  },
  {
    id: "nairobi-hex",
    name: "Nairobi Hex Geometric Rug",
    category: "modern",
    price: 9800,
    compareAt: 11500,
    badge: null,
    featured: true,
    stock: 12,
    image: "assets/images/geometric-nairobi.jpg",
    images: ["assets/images/geometric-nairobi.jpg"],
    material: "Low-pile synthetic, stain-resistant",
    pile: "Low · 8 mm",
    origin: "Contemporary mill · Kamukunji retail",
    colors: ["Navy", "Charcoal", "Ivory"],
    sizes: [
      { id: "sm", label: "120 × 170 cm", price: 7200 },
      { id: "md", label: "160 × 230 cm", price: 9800, default: true },
      { id: "lg", label: "200 × 290 cm", price: 13800 },
    ],
    summary: "Hex cubes in navy, grey and ivory — a modern rug that behaves in busy family rooms.",
    description:
      "Designed for concrete floors, open-plan lounges and rented flats where you want a statement without a museum piece. The low pile hides crumbs, the geometry hides the odd mark, and the palette works with black sofas or oak furniture alike.",
    care: "Vacuum freely. Most spills lift with a damp cloth. Suitable for light indoor-outdoor covered use.",
  },
  {
    id: "cloud-shag",
    name: "Cloud Shag Ivory Rug",
    category: "shag",
    price: 12500,
    compareAt: null,
    badge: "Softest",
    featured: true,
    stock: 7,
    image: "assets/images/shag-cloud.jpg",
    images: ["assets/images/shag-cloud.jpg"],
    material: "Deep polyester shag",
    pile: "High · 40 mm",
    origin: "Plush import · in-store now",
    colors: ["Ivory", "Warm cream"],
    sizes: [
      { id: "sm", label: "120 × 170 cm", price: 8900 },
      { id: "md", label: "160 × 230 cm", price: 12500, default: true },
      { id: "lg", label: "200 × 300 cm", price: 17200 },
    ],
    summary: "Forty millimetres of ivory shag — the rug people stand on in the shop and refuse to leave.",
    description:
      "Bedroom, nursery, or the corner of the sitting room where you watch TV. The pile is long, light-catching and outrageously soft. Best on a non-slip underlay (we stock those too). Not for muddy verandas — this one is for indoor spoiling.",
    care: "Gentle vacuum, suction only. Shake to revive the pile. Keep away from open flames and heavy office chairs.",
  },
  {
    id: "maasai-tribal",
    name: "Maasai Heritage Tribal Rug",
    category: "tribal",
    price: 8900,
    compareAt: 10500,
    badge: "Local favourite",
    featured: true,
    stock: 11,
    image: "assets/images/tribal-maasai.jpg",
    images: ["assets/images/tribal-maasai.jpg", "assets/images/about-store.jpg"],
    material: "Woven pile, cotton-blend",
    pile: "Low-medium",
    origin: "African-inspired design · Nairobi",
    colors: ["Crimson", "Black", "Ivory", "Earth"],
    sizes: [
      { id: "sm", label: "120 × 180 cm", price: 6400 },
      { id: "md", label: "160 × 230 cm", price: 8900, default: true },
      { id: "lg", label: "200 × 280 cm", price: 12400 },
    ],
    summary: "Shuka-inspired stripes and triangles — a Kenyan living-room rug with real presence.",
    description:
      "Bold crimson, ivory and black bands with triangle borders, drawn from the graphic language of Maasai cloth without copying any brand. It holds a room. Pair with dark timber, leather stools or a simple cream sofa.",
    care: "Vacuum regularly. Spot-clean. Colours are colourfast under normal indoor light.",
  },
  {
    id: "alnoor-prayer",
    name: "Al-Noor Deluxe Prayer Mat",
    category: "prayer",
    price: 1850,
    compareAt: 2300,
    badge: "Bestseller",
    featured: true,
    stock: 40,
    image: "assets/images/prayer-alnoor.jpg",
    images: ["assets/images/prayer-alnoor.jpg"],
    material: "Velvet with foam padding",
    pile: "Padded · ~18 mm",
    origin: "Premium prayer collection",
    colors: ["Emerald", "Gold embroidery"],
    sizes: [{ id: "std", label: "80 × 120 cm", price: 1850, default: true }],
    summary: "Emerald velvet, gold mihrab and tassels — a gift-worthy prayer mat with real padding.",
    description:
      "Soft velvet face, foam core, embroidered mosque arch and matching tassels. Comfortable for long standing and sujood. A staple we keep in depth because Eastleigh, South C and the CBD empty our shelves every Friday.",
    care: "Gentle brush or low vacuum. Do not wring. Air in shade if damp.",
  },
  {
    id: "safiri-prayer",
    name: "Safiri Travel Prayer Mat",
    category: "prayer",
    price: 950,
    compareAt: null,
    badge: null,
    featured: false,
    stock: 55,
    image: "assets/images/prayer-travel.jpg",
    images: ["assets/images/prayer-travel.jpg"],
    material: "Quilted microfibre",
    pile: "Thin padded",
    origin: "Travel collection",
    colors: ["Navy", "Gold geometric border"],
    sizes: [{ id: "std", label: "Folds to A4 · opens 60 × 100 cm", price: 950, default: true }],
    summary: "Navy quilted mat that folds to A4 — for the glove box, office drawer or suitcase.",
    description:
      "Light, cleanable and dignified. Gold lattice border, shaped mihrab, and a fold that actually stays flat when you open it. We sell these in twos: one for the car, one for the bag.",
    care: "Wipe with a barely damp cloth. Air dry. Do not iron the embroidery.",
  },
  {
    id: "coir-door",
    name: "Heritage Coir Door Mat",
    category: "door",
    price: 1200,
    compareAt: 1500,
    badge: null,
    featured: false,
    stock: 28,
    image: "assets/images/doormat-coir.jpg",
    images: ["assets/images/doormat-coir.jpg"],
    material: "Natural coconut coir + rubber border",
    pile: "Stiff scrape pile",
    origin: "Outdoor threshold",
    colors: ["Natural coir", "Black rubber"],
    sizes: [
      { id: "sm", label: "40 × 60 cm", price: 850 },
      { id: "md", label: "45 × 75 cm", price: 1200, default: true },
      { id: "lg", label: "60 × 90 cm", price: 1850 },
    ],
    summary: "Proper coir that scrapes Nairobi mud before it reaches your tiles.",
    description:
      "Thick coconut fibre in a black rubber frame. Lives on stone, concrete or a covered veranda. This is the mat that does the work so your indoor rugs last longer.",
    care: "Beat outdoors. Hose if needed and dry in the sun. Coir sheds lightly when new — that is normal.",
  },
  {
    id: "spa-wave",
    name: "Spa Wave Memory Foam Bath Mat",
    category: "bath",
    price: 1650,
    compareAt: 2100,
    badge: "Comfort",
    featured: true,
    stock: 22,
    image: "assets/images/bath-memory.jpg",
    images: ["assets/images/bath-memory.jpg", "assets/images/bath-long.jpg"],
    material: "Memory foam with microfibre face",
    pile: "Cushioned",
    origin: "Bathroom collection",
    colors: ["Warm grey"],
    sizes: [
      { id: "std", label: "50 × 80 cm", price: 1650, default: true },
      { id: "set", label: "Set of 2 (50×80 + 40×60)", price: 2650 },
    ],
    summary: "Quilted grey memory foam that makes a cold bathroom feel like a hotel.",
    description:
      "Wave-quilted microfibre over slow-rebound foam, with a non-slip base. Soft when you step out of the shower. Pair with our extra-long bath runner if you have a double vanity.",
    care: "Machine-wash cold in a laundry bag, gentle cycle. Lay flat to dry. Do not tumble on high.",
  },
  {
    id: "bloom-runner",
    name: "Bloom Kitchen Runner",
    category: "runners",
    price: 3900,
    compareAt: 4500,
    badge: "New",
    featured: true,
    stock: 10,
    image: "assets/images/kitchen-runner.jpg",
    images: ["assets/images/kitchen-runner.jpg"],
    material: "Low-pile printed runner, non-slip back",
    pile: "Low",
    origin: "Kitchen & hallway",
    colors: ["Aqua", "Rose", "Lemon wash"],
    sizes: [
      { id: "sm", label: "60 × 180 cm", price: 3200 },
      { id: "md", label: "60 × 240 cm", price: 3900, default: true },
      { id: "lg", label: "80 × 300 cm", price: 5200 },
    ],
    summary: "A wash of aqua, rose and lemon along the cooker run — kitchen floors, instantly kinder.",
    description:
      "Long, low and wipe-friendly. The abstract wash hides the odd splash of oil and brightens white or timber kitchens. Non-slip reverse so it stays put between fridge and sink.",
    care: "Vacuum. Spot-clean. Occasional gentle machine wash if the care label on your piece allows — ask in-store.",
  },
  {
    id: "midnight-runner",
    name: "Midnight Gallery Runner",
    category: "runners",
    price: 8800,
    compareAt: 10200,
    badge: null,
    featured: false,
    stock: 5,
    image: "assets/images/navy-runner.jpg",
    images: ["assets/images/navy-runner.jpg", "assets/images/hero.jpg"],
    material: "Oriental pile runner",
    pile: "Medium",
    origin: "Showroom gallery piece",
    colors: ["Midnight navy", "Gold", "Wine"],
    sizes: [
      { id: "md", label: "80 × 250 cm", price: 8800, default: true },
      { id: "lg", label: "80 × 350 cm", price: 11800 },
    ],
    summary: "A navy-and-gold corridor runner photographed hanging in our Kamukunji gallery.",
    description:
      "Deep indigo field with a lattice of gold and wine medallions. Made for long Nairobi hallways, hotel corridors and the path from sitting room to bedrooms. Comes rolled, ready to lay.",
    care: "Vacuum with the pile. Professional clean for oil or heavy soiling.",
  },
  {
    id: "shag-trio",
    name: "Kamukunji Shag Mat Trio",
    category: "bath",
    price: 2400,
    compareAt: 3000,
    badge: "Value",
    featured: false,
    stock: 18,
    image: "assets/images/folded-mats.jpg",
    images: ["assets/images/folded-mats.jpg", "assets/images/rolled-carpets.jpg", "assets/images/about-store.jpg"],
    material: "Plush indoor mats",
    pile: "Shag",
    origin: "Picked from our Kamukunji benches",
    colors: ["Teal", "Crimson", "Sand"],
    sizes: [{ id: "set", label: "Set of 3 · ~50 × 80 cm each", price: 2400, default: true }],
    summary: "Three plush mats — teal, crimson and sand — for bathroom, bedside and kitchen sink.",
    description:
      "We fold these on the wooden benches every morning. Buy the trio and split them around the house, or keep them as a colour-blocked bathroom set. A Kamukunji classic: good pile, honest price.",
    care: "Shake, gentle vacuum, or hand-wash and shade-dry.",
  },
  {
    id: "broadloom-cut",
    name: "Cut-to-Size Broadloom Carpet",
    category: "modern",
    price: 15500,
    compareAt: null,
    badge: "Made to fit",
    featured: false,
    stock: 15,
    image: "assets/images/rolled-carpets.jpg",
    images: ["assets/images/rolled-carpets.jpg", "assets/images/about-store.jpg"],
    material: "Wall-to-wall / room-fit carpet from the roll",
    pile: "Varies by roll — we cut in the yard",
    origin: "Kamukunji cutting yard",
    colors: ["Ask for today's rolls"],
    sizes: [
      { id: "room", label: "Typical bedroom ~12 m²", price: 15500, default: true },
      { id: "lounge", label: "Lounge ~20 m²", price: 24800 },
      { id: "quote", label: "Custom — WhatsApp measurements", price: 15500 },
    ],
    summary: "Carpet cut from the roll in our yard. Bring room measurements — we cut, you lay or we send a fitter.",
    description:
      "The standing rolls at the back of the shop are not decoration. We cut bedrooms, offices, mosques, hotel corridors and car-boot liners. Price shown is a starting bedroom pack; send length × width on WhatsApp for an exact quote, including underlay.",
    care: "Depends on the fibre we cut for you. We include a care slip with every roll.",
  },
  {
    id: "everyday-pack",
    name: "Everyday Indoor Mat Pack",
    category: "door",
    price: 2800,
    compareAt: 3400,
    badge: null,
    featured: false,
    stock: 16,
    image: "assets/images/rack-mats.jpg",
    images: ["assets/images/rack-mats.jpg", "assets/images/about-store.jpg"],
    material: "Mixed indoor mats, rubber or fabric back",
    pile: "Low",
    origin: "Rack selection",
    colors: ["Assorted stripes, plains and checks"],
    sizes: [{ id: "pack", label: "Pack of 4 mixed indoor mats", price: 2800, default: true }],
    summary: "Four indoor mats off the rack — kitchen, corridor, office and rental-ready.",
    description:
      "The hanging rack is how Kamukunji actually shops: flip, feel, take. This pack is our edit of four indoor mats that survive real houses. Colours vary with stock — we always send a balanced mix.",
    care: "Shake or vacuum. Most pieces are spot-clean only.",
  },
  {
    id: "bath-long",
    name: "Extra-Long Bath Runner",
    category: "bath",
    price: 2100,
    compareAt: 2500,
    badge: null,
    featured: false,
    stock: 14,
    image: "assets/images/bath-long.jpg",
    images: ["assets/images/bath-long.jpg", "assets/images/bath-memory.jpg"],
    material: "Memory foam microfibre",
    pile: "Cushioned",
    origin: "Bathroom collection",
    colors: ["Chocolate", "Grey on request"],
    sizes: [{ id: "std", label: "45 × 120 cm", price: 2100, default: true }],
    summary: "A long chocolate memory-foam runner for double vanities and shower-to-door paths.",
    description:
      "Same hotel foam as the Spa Wave, stretched to runner length so wet feet never hit cold tiles. Non-slip reverse. A small upgrade that changes a bathroom.",
    care: "Machine-wash cold, laundry bag, lay flat to dry.",
  },
  {
    id: "family-prayer",
    name: "Family Prayer Mat — Extra Wide",
    category: "prayer",
    price: 3200,
    compareAt: 3800,
    badge: null,
    featured: false,
    stock: 12,
    image: "assets/images/prayer-alnoor.jpg",
    images: ["assets/images/prayer-alnoor.jpg", "assets/images/prayer-travel.jpg"],
    material: "Velvet + thick foam",
    pile: "Padded",
    origin: "Family collection",
    colors: ["Emerald & gold"],
    sizes: [{ id: "xl", label: "110 × 160 cm", price: 3200, default: true }],
    summary: "Wider, longer, thicker — for two worshippers or anyone who wants more room to pray.",
    description:
      "The Al-Noor design scaled up. Extra foam, extra width, still elegant enough to leave out in a sitting room. Popular for Iftar hosting and as a wedding gift.",
    care: "Gentle vacuum. Shade dry. Do not machine-wash.",
  },
];

const TESTIMONIALS = [
  {
    quote: "I came for a door mat and left with a living-room rug. They let me stand on three options until the colour was right. Delivery to South C the same afternoon.",
    name: "Amina K.",
    place: "South C, Nairobi",
  },
  {
    quote: "Bought prayer mats for the office musalla. Quality is honest, prices are Kamukunji-fair, and they packed them properly for town.",
    name: "Hassan M.",
    place: "CBD",
  },
  {
    quote: "The Maasai tribal rug is the first thing guests notice. WhatsApped my floor photo, they told me the size. That kind of help is rare.",
    name: "Brian O.",
    place: "Westlands",
  },
  {
    quote: "We outfit rentals. The geometric rugs and mat packs survive tenants and still look considered. I reorder every quarter.",
    name: "Faith W.",
    place: "Kitengela",
  },
];
